### PR TITLE
Allow definition of skeletons outside the skeleton folder

### PR DESCRIPTION
**Pull request by tsteinruecken**
This replaces https://github.com/viur-framework/server/pull/104

### CODE REVIEW

**Comment by tsteinruecken** [comment]
Hm.. interesting point. I think we have to flag the _elements skel somehow as abstract - so it can't be used directly (and get a kindName assigned) but you still can (and have to!) derive from it. Maybe we can come up with a specific pre/postFix for class-names for such skeletons (xxxBaseSkel? xxxAbstractSkel?).

**Comment by phorward** [comment]
> Hm.. interesting point. I think we have to flag the _elements skel somehow as abstract - so it can't be used directly (and get a kindName assigned) but you still can (and have to!) derive from it. Maybe we can come up with a specific pre/postFix for class-names for such skeletons (xxxBaseSkel? xxxAbstractSkel?).

That would be an adequate solution for me with a straightforward distinction of what can be used directly and what must be sub-classed! Can you implement this in your PR?

**Comment by tsteinruecken** [comment]
My preferred solution would be explicitly setting kindName to None in abstract Skel. Removing them from the server is a bad idea - probably for the same reasons you keept fileBaseSkel etc. If they have no kind set, are extended by the project and you don't name your extended skeleton exactly userSkel / pageSkel in your project, you end up with two different definitions for different kinds.

**Comment by phorward** [comment]
> My preferred solution would be explicitly setting kindName to None in abstract Skel.

Well this is not straightforward to me, but a compromise that works.

**Pull request merged**
