### PR TITLE
Proposal for an improved updateRelations

### PR DESCRIPTION
**Pull request by phorward**
This function contains functions which also cleans up viur-relations from invalid entries. Code has been re-arranged for more clarity.

### CODE REVIEW

**Comment by tsteinruecken** [comment]
You can't do this. If you run this code you'll create inconsistencies in your database. There's a fundamental difference in "this kind does not exist anymore" (Which implies there also cannot be a relationalBone pointing to it) and "this entity had been deleted" (Where is it absolutely valid to have a relation pointing towards it). If you remove that database object, it will disappear from relational queries, despite still referencing objects. Also, they will be recreated as soon the referencing entity is saved again.

**Comment by phorward** [comment]
What is exactly the point I can't do here?

1. My implementation of this function looks much more "understandable" than the current implementation
2. There are 3 lines in this PR where `db.Delete()` is called - not all of them can be wrong, especially the last one where I delete a viur-relation entry that refers to a bone which is not existing anymore. I have a huge, older database with tons of these entities which are invalid and must be removed to decrease the time updateRelations is running on these queries, because objects that absolutely don't have any relevance are touched.

**Comment by phorward** [comment]
Solution proposal:
1. Remove the db.Delete() and also the loggings, replace by useful comments
2. Writea vacuumRelations-Task to clear all relations manually.

**Comment by phorward** [comment]
Hello, I've recently updated this pull request to a (hopefully) better solution:

- Commented and optionally cleaning `updateRelations` function
- A way to call `Skeleton.toDB()` with parameters that are passed to updateRelations
- Cleaned-up rebuildSearchIndex task that removes the old "compact" bone which was deactived and got no real usage.

The pull request was tested several times. It might be breaking, when toDB() is overridden without **kwargs pass-through.

**Comment by tsteinruecken** [comment]
I have still some suggestions:
- replace booleanBone with a stringBone which must be filled with "YES" (https://github.com/viur-framework/server/blob/master/skeleton.py#L1038) to prevent accidental triggering
- move the code to a separate task (away from rebuildSearchIndex) and call updateRelations directly- That way we can keep the signature of skel.toDB() - and fix the currently inverted semantic (if you have an relation from user --> file which had been removed, you'd now have to call rebuildSearchIndex on **file** to have the outgoing relation in user removed (and it would remove **any** stale relation _to_ file, not just the one from user).
- i just discovered that i misinterpreted str(srcRel.key().parent()) (https://github.com/viur-framework/server/pull/144/files#diff-708c2c25d61bdb083539577332454bdbR1018) as destination key in my last comment. It's correct that the destination key may not exist anymore, but the srcKey should never vanish. I think that can only happen if you remove an entry created by skel.toDB() by db.Delete() - which is an error to do so. You'll not only end up with stale relations but also with never deleted files; locked uniqueProperties and so on. Not sure if we should handle this case at all (or also have to implement cleanups for these other cases?) - again, it's invalid to do so.
- Maybe we should start over in a new branch?

**Comment by phorward** [comment]
Hi,
I've just updated this PR to an approach with lesser function signature changes.

> replace booleanBone with a stringBone which must be filled with "YES" (https://github.com/viur-framework/server/blob/master/skeleton.py#L1038) to prevent accidental triggering
Why? booleanBone is the correct way to express a switch ON/OFF. The user has to know what switching it ON means (in my opinion, in most cases its better for having a clean database)

> move the code to a separate task (away from rebuildSearchIndex) and call updateRelations directly...
I now call updateRelations from rebuildSearchIndex. It works fine.

> i just discovered that i misinterpreted str(srcRel.key().parent())
can you please give a concrete point in the code which part should be changed? It is correct, that using db.Delete() instead of skel.delete() is invalid, but anyway its possible and might be wanted.

**Comment by phorward** [comment]
> Maybe we should start over in a new branch?

I think is OK here to use the squash merging feature to end with one single commit in the develop branch history.

**Comment by tsteinruecken** [comment]
Replaced by #169.

**Pull request closed without merging**
